name: Arduino Bulut Derleyici

on:
  workflow_dispatch:
    inputs:
      sketch_code:
        description: 'Kod'
        required: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino CLI Kur
        uses: arduino/setup-arduino-cli@v2
        with:
          version: "latest"

      - name: Klasor Olustur
        run: mkdir -p MySketch

      - name: Kodu Yaz
        run: |
          cat << 'EOF' > MySketch/MySketch.ino
          ${{ github.event.inputs.sketch_code }}
          EOF

      - name: Derle (Hicbir sey indirmeden)
        run: |
          # --no-color: Logları sadeleştirir
          # --offline: İnternete bağlanmasını yasaklar
          arduino-cli compile --fqbn arduino:avr:uno MySketch --output-dir ./output --offline
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: compiled-hex
          path: output/*.hex
