name: Arduino Bulut Derleyici

on:
  workflow_dispatch:
    inputs:
      sketch_code:
        description: 'Arduino Kodu'
        required: true
      libraries:
        description: 'Kütüphaneler'
        required: false
        default: ''

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino CLI Kur
        uses: arduino/setup-arduino-cli@v2
        with:
          version: "latest"

      - name: Platformu Hazirla
        run: |
          # Hata almamak için sessiz modda kuruyoruz
          arduino-cli core update-index
          arduino-cli core install arduino:avr --quiet

      - name: Sketch Dosyasını Oluştur
        run: |
          mkdir -p MySketch
          # Kodu temiz bir şekilde dosyaya yaz
          cat << 'EOF' > MySketch/MySketch.ino
          ${{ github.event.inputs.sketch_code }}
          EOF

      - name: Derle (Compile)
        run: |
          mkdir -p output
          arduino-cli compile --fqbn arduino:avr:uno MySketch --output-dir ./output

      - name: HEX Yayınla
        uses: actions/upload-artifact@v4
        with:
          name: compiled-hex
          path: output/*.hex
