name: Arduino Bulut Derleyici

on:
  workflow_dispatch:
    inputs:
      sketch_code:
        description: 'Arduino Kodu'
        required: true
      libraries:
        description: 'Kütüphaneler'
        required: false
        default: ''

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino CLI Kur
        uses: arduino/setup-arduino-cli@v2
        with:
          version: "latest"

      - name: Platformu Kur (Offline Mod)
        run: |
          # İnternete sormadan direkt AVR çekirdeğini yüklemeyi dene
          arduino-cli core install arduino:avr --quiet || true

      - name: Sketch Dosyasını Oluştur
        run: |
          mkdir -p MySketch
          cat << 'EOF' > MySketch/MySketch.ino
          ${{ github.event.inputs.sketch_code }}
          EOF

      - name: Derle (Compile)
        run: |
          # --no-color ve --warnings none ile çıktıyı sadeleştir
          mkdir -p output
          arduino-cli compile --fqbn arduino:avr:uno MySketch --output-dir ./output --warnings none

      - name: HEX Yayınla
        uses: actions/upload-artifact@v4
        with:
          name: compiled-hex
          path: output/*.hex
