name: Arduino Bulut Derleyici

on:
  workflow_dispatch:
    inputs:
      sketch_code:
        description: 'Kod'
        required: true
      libraries:
        description: 'Kütüphaneler (Virgül ile ayırın)'
        required: false
        default: ''

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino CLI El ile Kur
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/bin" >> $GITHUB_PATH

      - name: Derleyici ve Kütüphaneleri Hazırla
        run: |
          ./bin/arduino-cli core install arduino:avr
          if [ "${{ github.event.inputs.libraries }}" != "" ]; then
            # Virgülle ayrılmış kütüphaneleri düzgünce parçala ve tırnak içinde kur
            echo "${{ github.event.inputs.libraries }}" | tr ',' '\n' | while read lib; do
              [ -z "$lib" ] && continue
              ./bin/arduino-cli lib install "$lib" || true
            done
          fi

      - name: Sketch ve Derleme
        run: |
          mkdir -p MySketch
          cat << 'EOF' > MySketch/MySketch.ino
          ${{ github.event.inputs.sketch_code }}
          EOF
          ./bin/arduino-cli compile --fqbn arduino:avr:uno MySketch --output-dir ./output

      - name: HEX Yayınla
        uses: actions/upload-artifact@v4
        with:
          name: arduino_build  # Zip dosyasının adı
          path: output/MySketch.ino.hex # Sadece bu dosyayı al
          if-no-files-found: error
