name: Arduino Bulut Derleyici

on:
  workflow_dispatch:
    inputs:
      sketch_code:
        description: 'Kod'
        required: true
      libraries:
        description: 'Kütüphaneler (Virgül ile ayırın)'
        required: false
        default: ''

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino CLI El ile Kur
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/bin" >> $GITHUB_PATH

      - name: Derleyici ve Kütüphaneleri Hazırla
        run: |
          ./bin/arduino-cli core install arduino:avr
          # Eğer input olarak kütüphane girilmişse onları kur
          if [ "${{ github.event.inputs.libraries }}" != "" ]; then
            # Virgülle ayrılmış kütüphaneleri döngüyle kurar
            IFS=',' read -ra ADDR <<< "${{ github.event.inputs.libraries }}"
            for i in "${ADDR[@]}"; do
              ./bin/arduino-cli lib install "$i" || true
            done
          fi

      - name: Sketch ve Derleme
        run: |
          mkdir -p MySketch
          cat << 'EOF' > MySketch/MySketch.ino
          ${{ github.event.inputs.sketch_code }}
          EOF
          ./bin/arduino-cli compile --fqbn arduino:avr:uno MySketch --output-dir ./output

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: compiled-hex
          path: output/*.hex
