name: Arduino Bulut Derleyici

on:
  workflow_dispatch:
    inputs:
      sketch_code:
        description: 'Arduino Kodu'
        required: true
      libraries:
        description: 'Kütüphaneler'
        required: false
        default: ''

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sketch Dosyasını Hazırla
        run: |
          mkdir -p MySketch
          cat << 'EOF' > MySketch/MySketch.ino
          ${{ github.event.inputs.sketch_code }}
          EOF

      - name: Derle (Arduino CLI Docker)
        uses: SaneBrain/arduino-cli-action@v2
        with:
          fqbn: "arduino:avr:uno"
          sketch-path: "./MySketch"
          output-dir: "./output"

      - name: HEX Dosyasını Yayınla
        uses: actions/upload-artifact@v4
        with:
          name: compiled-hex
          path: output/*.hex
